### ISSUE TITLE
Issues Upgrading to Laravel 10

### ISSUE THREAD

**Issue by RussDaley-CS** [avramovic/aws-cron-job#11]
I'm upgrading from laravel v9 to v10. But running into this error:

 - avram/aws-cron-job v0.4.0 requires illuminate/console ^7.0|^8.0 -> satisfiable by illuminate/console[v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27].
 - Only one of these can be installed: illuminate/console[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.39.0], laravel/framework[v10.0.0, ..., v10.39.0]. laravel/framework replaces illuminate/console and thus cannot coexist with it.

Do you have any plans to support Laravel 10?

**Comment by avramovic** [comment]
Sorry, I don't have any L 10 projects maintaining right now.

Can you try running the following command in your project folder:

`composer require avram/aws-cron-job:dev-laravel-10`

If it works, I'll merge it in main branch

**Comment by RussDaley-CS** [comment]
I removed this package last week, because from what I could tell Laravel has this functionality built in. [https://laravel.com/docs/10.x/scheduling#running-tasks-on-one-server](https://laravel.com/docs/10.x/scheduling#running-tasks-on-one-server) Tell me if I'm wrong.

But to help out I've installed your updated branch on my Laravel 10 project, and there were no package conflicts.

**Comment by avramovic** [comment]
Thank you very much!

Yes, it seems newer versions of Laravel have this built in, provided that you are using central cache, as mentioned in the linked documentation.
