### ISSUE TITLE
Where to put the command?

### ISSUE THREAD

**Issue by winkbrace** [avramovic/aws-cron-job#5]
First off, thanks for open sourcing your package. :)

Following your clear guide, I completed all steps in the setup. Now I'm at the final point in the readme. But it's not clear to me where to put the aws:schedule:run command. In the `.ebextensions` folder, in a cron job in an instance, or somewhere else?

**Comment by avramovic** [comment]
It depends how you are setting up your cron jobs. I have a script in `.ebextensions/crontab.config` folder which creates cron job for the `webapp` user, something like this:

```
container_commands:
  01_create_home_folder_for_webapp:
    command: "mkdir /home/webapp && chown webapp:webapp /home/webapp || exit 0"
  02_remove_old_cron_jobs:
    command: "crontab -r -u webapp || exit 0"
  03_cronjobs:
    command: "crontab .ebextensions/crontab -u webapp"
```

And then in `.ebextensions/crontab` I have this:

```
* * * * * . /opt/elasticbeanstalk/support/envvars && php /var/app/current/artisan aws:schedule:run >> /var/app/current/storage/logs/crontab.log
```

**Comment by winkbrace** [comment]
Cool, thanks! :)
