### ISSUE TITLE
Undefined variable: schedule {"exception":"[object] (ErrorException(code: 0): Undefined variable: schedule at /var/app/current/vendor/avram/aws-cron-job/src/Commands/AwsScheduleRunCommand.php:70)

### ISSUE THREAD

**Issue by adydev15** [avramovic/aws-cron-job#8]
Thanks for creating a package that is addressing AWS cron stuff in good way . 

I have followed your guide and steps to use it.After completing it all it is executing on the server but it is throwing error as below . 

**Note :  I am using 0.2.1 version of your package as i am using laravel 6.*** 

[stacktrace]
#0 /var/app/current/vendor/avram/aws-cron-job/src/Commands/AwsScheduleRunCommand.php(70): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined varia...', '/var/app/curren...', 70, Array)
#1 /var/app/current/vendor/avram/aws-cron-job/src/Commands/AwsScheduleRunCommand.php(47): Avram\\AwsCronJob\\Commands\\AwsScheduleRunCommand->runIfEnabled()
#2 /var/app/current/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Avram\\AwsCronJob\\Commands\\AwsScheduleRunCommand->handle(Object(Illuminate\\Console\\Scheduling\\Schedule), Object(Illuminate\\Events\\Dispatcher))
#3 /var/app/current/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /var/app/current/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#5 /var/app/current/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#6 /var/app/current/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#7 /var/app/current/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call(Array)
#8 /var/app/current/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#9 /var/app/current/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#10 /var/app/current/vendor/symfony/console/Application.php(1009): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#11 /var/app/current/vendor/symfony/console/Application.php(273): Symfony\\Component\\Console\\Application->doRunCommand(Object(Avram\\AwsCronJob\\Commands\\AwsScheduleRunCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#12 /var/app/current/vendor/symfony/console/Application.php(149): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#13 /var/app/current/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 /var/app/current/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 {main}
"}

can you please guide me on this ..?

**Comment by avramovic** [comment]
Hi!

I just tried with new L6 project and v0.2.1 and didn't get the error, but by looking at the code I see where it is coming from. Can you try to update to 0.2.2 and try again? 

Simply run `composer require avram/aws-cron-job:^0.2` again and it should update it to 0.2.2

**Comment by adydev15** [comment]
Hi 

thanks for reverting back.

It is working fine now ! 

Thanks !
