### ISSUE TITLE
Laravel 9 Support

### ISSUE THREAD

**Issue by ruurdkrekt** [avramovic/aws-cron-job#9]
Would it be possible to add Laravel 9 support? From my understanding it's the illuminate/console package in composer.json that requires amending to include version 9.

**Comment by avramovic** [comment]
Hi! I don't have any L9 projects right now, didn't get to update them yet. Can you try temporarily to install from branch `laravel-9` and let me know if it works. If it does work, I'll merge #10 to master (and bump the version). 

```
composer require avram/aws-cron-job:dev-laravel-9
```

**Comment by ruurdkrekt** [comment]
Hey! Thanks for the quick reply, it's much appreciated. I have a few free hours tomorrow evening, will give it a try then. Hope you have a fab day 😀

**Comment by ruurdkrekt** [comment]
Evening, pleased to let you know that your amendments work very well and this package runs smoothly on Laravel 9.

**Comment by avramovic** [comment]
Thank you very much for testing this! I've merged that branch to master and released 0.4.1 with L9 support. You can safely revert to ^0.4 as it will install the latest version!

`composer require avram/aws-cron-job:^0.4`
